
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        run: |
          # Create artifact directory
          mkdir -p ./_site
          # Copy build output to artifact directory
          cp -r ./dist/* ./_site
          # Use GitHub CLI to create and upload artifact
          gh artifact upload _site --dir=./_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        run: |
          # Use GitHub CLI to deploy to Pages
          gh pages deploy --dir=_site --source=artifact:_site
          # Get the deployment URL
          DEPLOY_URL=$(gh pages status --json url -q .url)
          echo "page_url=$DEPLOY_URL" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
